name: flutter_app_template
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  dio: ^5.3.0
  logger: any
  flutter_dotenv: ^5.1.0
  hive: ^2.2.3
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.4
  flutter_barcode_scanner: ^2.0.0
  dart_random_choice: ^0.2.0
  gif_view: ^0.4.0
  path_provider: ^2.1.0
  path: ^1.8.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  font_awesome_flutter: ^10.5.0
  uuid: ^3.0.7
  health: ^8.0.0
  permission_handler: ^11.0.1
  is_first_run: ^1.0.0
  percent_indicator: ^4.2.3
  flutter_fgbg: ^0.3.0
  just_audio: ^0.9.35

  flutter_fortune_wheel:
    path: 'flutter_fortune_wheel'


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  surf_lint_rules: ^3.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  json_serializable: ^6.7.1
  

flutter:
  uses-material-design: true


  assets:
    - assets/audio/
    - assets/configs/
    - assets/pets/
    - assets/pets/gifs/